version: '3'

services:
  web:
    build: .
    container_name: Apache_Container
    volumes:
      - ./root-folder:/var/www/html
      - ./apache-config:/etc/apache2  # Maps host's apache-config directory to container's Apache config
    ports:
      - "8089:80"
    restart: always

