version: "3.8"

services:
  tomcat:
    build: .
    container_name: tomcat_server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat_logs:/usr/local/tomcat/logs
      - ./tomcat_webapps:/usr/local/tomcat/webapps
    environment:
      - CATALINA_HOME=/usr/local/tomcat

volumes: {}

