version: "3"

services:
  tomcat:
    build: .
    container_name: tomcat_server
    restart: always
    ports:
      - "8080:8080"
    volumes:
      - ./tomcat_logs:/usr/local/tomcat/logs
      - ./tomcat_webapps:/usr/local/tomcat/webapps
      - ./tomcat_conf:/usr/local/tomcat/conf  # Mount the Tomcat configuration folder
    environment:
      - CATALINA_HOME=/usr/local/tomcat

volumes: {}

