version: "3"

services:
  mysql:
    container_name: mysql_container
    build:
      context: .                 
      dockerfile: Dockerfile         
    restart: unless-stopped           
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: test_db
      MYSQL_USER: test
      MYSQL_PASSWORD: password
    volumes:
      - ./mysql_data:/var/lib/mysql          
      - ./mysql-config:/etc/mysql      
    ports:
      - "3306:3306"                                  
    networks:
      - mysql_network                                 

networks:
  mysql_network:
    driver: bridge
